### ISSUE TITLE
Minor nits on v00

### ISSUE THREAD

**Issue by rharolde** [alex-nicat/ietf-dprive-phase2-requirements#33]
9.1.  The User Perspective and Use Cases

"Qname minimisation [RFC7816], reducing the amount of information which is absolutely necessary to resolve a query"

"information which is" - > "information to that which is"

"However, the user has never a chance to identify which data
   was exposed to which authoritative party (via which path)."

"has never" - > "never has"

**Comment by bjovereinder** [comment]
Thanks!  Corrections are incorporated in the draft.
